**Welcome to numpy tutorial**

In [1]:
import numpy as np

In [2]:
myarr = np.array([[3,6,37,7]], np.int64)

In [3]:
myarr[0,1]

6

In [4]:
myarr.shape

(1, 4)

In [5]:
myarr.dtype

dtype('int64')

In [6]:
myarr[0,1] = 30

In [7]:
myarr

array([[ 3, 30, 37,  7]], dtype=int64)

In [8]:
print("hello")

hello


In [9]:
print("hi")

hi


**Array Creation : Conversion from other Python structures**

In [10]:
listarray = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [11]:
listarray

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [12]:
listarray.dtype

dtype('int32')

In [13]:
listarray.shape

(3, 3)

In [14]:
listarray.size

9

In [15]:
np.array({12,13,14})

array({12, 13, 14}, dtype=object)

**Array Creation : Intrinsic numpy array array creation objects(e.g., arange, ones, zeros, etc.)**

In [16]:
zeros = np.zeros((3,8))

In [17]:
zeros

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [18]:
range1 = np.arange(20)

In [19]:
range1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [20]:
ones = np.ones((2,5))

In [21]:
ones

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [22]:
sample = np.ones((3,5))

In [23]:
sample

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [24]:
samplekarange = np.arange(30)   #arange use to make an array, in bracket there is size of array

In [25]:
samplekarange

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [26]:
lispace = np.linspace(1,50,5)  #it give  1 to 50 elements with thier between same disatnce that is th third element is denoted as distance

In [27]:
lispace

array([ 1.  , 13.25, 25.5 , 37.75, 50.  ])

In [28]:
emp1 = np.empty((2,8))  #give a random value in the array

In [29]:
emp1

array([[6.23042070e-307, 4.67296746e-307, 1.69121096e-306,
        1.29061074e-306, 8.34441742e-308, 1.78022342e-306,
        6.23058028e-307, 9.79107872e-307],
       [6.89807188e-307, 7.56594375e-307, 6.23060065e-307,
        1.78021527e-306, 8.34454050e-308, 1.11261027e-306,
        1.15706896e-306, 1.33512173e-306]])

In [30]:
emp_like = np.empty_like(lispace)  # purana array ka size copy karke new array banata he..

In [31]:
emp_like

array([ 1.  , 13.25, 25.5 , 37.75, 50.  ])

In [32]:
ide = np.identity(45)

In [33]:
ide

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [34]:
ide.shape

(45, 45)

In [35]:
arr = np.arange(99)

In [36]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [37]:
arr.reshape(3,33) # (3 * 33 = 99) then it runs otherwise it give an error

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [38]:
arr.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [39]:
arr.shape

(99,)

In [40]:
list1 = [[1,2,3],[4,5,6],[7,1,0]]

In [41]:
list1

[[1, 2, 3], [4, 5, 6], [7, 1, 0]]

In [42]:
ar = np.array(list1)

In [43]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [44]:
ar.sum(axis=0)   #axis=0  give column addition

array([12,  8,  9])

In [45]:
ar.sum(axis=1)  #axis=1  give row addition

array([ 6, 15,  8])

In [46]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [47]:
ar.T        #transpose array

array([[1, 4, 7],
       [2, 5, 1],
       [3, 6, 0]])

In [48]:
ar.flat

In [49]:
for sample in ar.flat:
    print(sample)

1
2
3
4
5
6
7
1
0


In [50]:
ar.ndim   # array ka dimension batata he

2

In [51]:
ar.shape

(3, 3)

In [52]:
ar.size

9

In [53]:
ar.nbytes   #total kitna bytes consume kiya he array ne vo batata he

36

In [54]:
one = np.array([1,4,67,443,665,321,2])

In [55]:
one

array([  1,   4,  67, 443, 665, 321,   2])

In [56]:
one.argmax()   #maximum value konse position par he uska index deta he

4

In [57]:
one.argmin()  #minimum value konse position par he uska index deta he

0

In [58]:
one.argsort()    #sorting karta he but uske indexing ke nusar, uska insex batata he

array([0, 6, 1, 2, 5, 3, 4], dtype=int64)

In [59]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [60]:
ar.argmin()   #pehele array ko sidha karta he and then 0 sabse chota he to uska index deta he

8

In [61]:
ar.argmax()

6

In [62]:
ar.argmax(axis=0)   #column dekhe uske hisab se max value batata he

array([2, 1, 1], dtype=int64)

In [63]:
ar.argmax(axis=1)

array([2, 2, 0], dtype=int64)

In [64]:
ar.argsort(axis=0)

array([[0, 2, 2],
       [1, 0, 0],
       [2, 1, 1]], dtype=int64)

In [65]:
ar.argsort(axis=1)

array([[0, 1, 2],
       [0, 1, 2],
       [2, 1, 0]], dtype=int64)

In [66]:
ar2 = np.array([[1, 2, 3],[4, 5, 6],[7, 1, 0]])

In [67]:
ar2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [68]:
   ar + ar2

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14,  2,  0]])

In [69]:
ar * ar2

array([[ 1,  4,  9],
       [16, 25, 36],
       [49,  1,  0]])

In [70]:
ar.sum()

29

In [71]:
ar.max()

7

In [72]:
ar.min()

0

In [73]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [74]:
np.sqrt(ar)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 1.        , 0.        ]])